"""add roles in db

Revision ID: b0ed90f07585
Revises: 
Create Date: 2026-03-03 11:55:16.969062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ed90f07585'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

roles_tables = sa.Table(
    "roles", 
    sa.MetaData(),
    sa.Column("id", sa.Integer, primary_key=True),
    sa.Column("name", sa.String)
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        roles_tables,
        [
            {"name": "USER"},
            {"name": "ADMIN"}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM roles WHERE name IN ('ADMIN', 'USER')")
    # ### end Alembic commands ###
